### ISSUE TITLE
sorry i missed the github email can you give the "patch" you were talking about

### ISSUE THREAD

**Issue by hello-lab** [olegyadrov/TheFriendlyGhost#2]
....

**Comment by olegyadrov** [comment]
Find ServerManager.Start, scroll down until you see "mov dl,04", replace with "mov dl,06".
ServerManager.Start is at GameAssembly.dll+155DE90 in 0.5.2.0, the instructions you're looking for are at GameAssembly.dll+155DFBD. The next call (call GameAssembly.dll+717440) is actually Photon.Realtime.Room.set_MaxPlayers.
